// настройки приложения, тексты сообщений об ошибках, селекторы элементов

export default {
  AUTH_BUTTON: document.querySelector('.js-button-auth'),
  SAVEDNEWS_LINK: document.querySelector('.js-savednews-link'),
  LOGOUT_BUTTON: document.querySelector('.js-button-logout'),
  OPEN_BUTTON_MENU: document.querySelector('.js-button-menu-open'),
  CLOSE_BUTTON_MENU: document.querySelector('.js-button-menu-close'),
  AUTH_BUTTON_MENU: document.querySelector('.js-button-menu-auth'),
  LOGOUT_BUTTON_MENU: document.querySelector('.js-button-menu-logout'),
  SAVEDNEWS_LINK_MENU: document.querySelector('.js-link-menu-savednews'),
  MENU_POPUP: document.querySelector('.js-popup-menu'),
  SIGNIN_POPUP: document.querySelector('.js-popup-sign-in'),
  SIGNUP_POPUP: document.querySelector('.js-popup-sign-up'),
  SUCCESS_POPUP: document.querySelector('.js-popup-success'),
  CLOSE_SIGNUP: document.querySelector('.js-close-sign-up'),
  CLOSE_SIGNIN: document.querySelector('.js-close-sign-in'),
  CLOSE_SUCCESS: document.querySelector('.js-close-success'),
  SIGNUP_POPUP_LINK: document.querySelector('.js-popup-link-sign-up'),
  SIGNIN_POPUP_LINK: document.querySelector('.js-popup-link-sign-in'),
  SUCCESS_POPUP_LINK: document.querySelector('.js-popup-link-success'),
  SIGNIN_FORM: document.forms['sign-in'],
  SIGNUP_FORM: document.forms['sign-up'],
  SIGNUP_SUBMIT_BUTTON: document.querySelector('.js-submit-sign-up'),
  SIGNIN_SUBMIT_BUTTON: document.querySelector('.js-submit-sign-in'),
  SIGNUP_ERRORS: document.querySelectorAll('.js-sign-up-error'),
  SIGNIN_ERRORS: document.querySelectorAll('.js-sign-in-error'),
  SEARCH_FORM: document.forms.search,
  SEARCH_BUTTON: document.querySelector('.search__button'),
  NEWSCARDS_CONTAINER: document.querySelector('.article-grid'),
  RESULTS_NOTFOUND: document.querySelector('.results__not-found'),
  RESULTS_PRELOADING: document.querySelector('.results__preloading'),
  SHOWMORE_BUTTON: document.querySelector('.results__more'),
  RESULTS_CONTAINER: document.querySelector('.results__container'),
  RESULTS_ERROR: document.querySelector('.results__not-found-text'),
  RESULTS_TITLE_ERROR: document.querySelector('.results__not-found-title'),
};
